apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hw-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/misgav777/hw-k8s-config.git
    targetRevision: HEAD
    path: hw-app
    helm:
      valueFiles:
        - ../environments/prd/values.yaml
      releaseName: hw-app-production
  destination:
    server: https://kubernetes.default.svc
    namespace: prd  
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true