apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hw-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/misgav777/hw-k8s-config.git
    targetRevision: HEAD
    path: hw-app
    helm:
      valueFiles:
        - ../environments/stg/values.yaml
      releaseName: hw-app-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: stg  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true