replicaCount: 2

image:
  repository: 713881821143.dkr.ecr.ap-south-1.amazonaws.com/stg/hw-app
  pullPolicy: IfNotPresent
  tag: "37a62aac71078db31c8f1d67f1b66a1a58e92dae"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Staging environment ingress
ingress:
  enabled: true  
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rate-limit-rps: "10"
  host: 
  path: /stg

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional volumes if needed
volumes: []

# Environment variables
env:
  NODE_ENV: staging
  LOG_LEVEL: info