replicaCount: 1
image:
  repository: 713881821143.dkr.ecr.ap-south-1.amazonaws.com/dev/hw-app
  pullPolicy: IfNotPresent
  tag: latest


service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Default to NGINX Ingress Controller
ingress:
  enabled: true  
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  host: ""


resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

