# Production Environment Values
replicaCount: 3

image:
  repository: 713881821143.dkr.ecr.ap-south-1.amazonaws.com/prd/hw-app
  pullPolicy: Always
  tag: "1.2.11"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Production environment ingress with TLS
ingress:
  enabled: true  
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rate-limit-rps: "50"
  host: 
  path: /prd


# Production gets more resources
resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Possible volumes for production (example for TLS or config)
volumes: []

# Add auto-scaling for production
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Environment variables
env:
  NODE_ENV: production
  LOG_LEVEL: warn
  ENABLE_CACHING: "true"