# Development Environment Values
replicaCount: 1

image:
  repository: 713881821143.dkr.ecr.ap-south-1.amazonaws.com/dev/hw-app
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Dev environment ingress
ingress:
  enabled: true  
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  host: ""
  path: /dev

# Minimal resources for dev
resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Dev environment might need debug volume
volumes: []

# Environment variables
env:
  NODE_ENV: development
  LOG_LEVEL: debug